FROM openapitools/openapi-generator-cli:v4.2.1

COPY update_schema.sh /helpers/update_schema.sh
RUN chmod +x /helpers/update_schema.sh

VOLUME /openapi

# Original API schema is located at https://evr-test.azurewebsites.net/api/openapi.json
CMD ["/helpers/update_schema.sh", "https://evr-test.azurewebsites.net/api/openapi-generator-compatible.json"]
