# coding: utf-8

# flake8: noqa
"""
    EVR API

    OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.  # noqa: E501

    The version of the OpenAPI document: 0.14-dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.add_measurement_act_request import AddMeasurementActRequest
from openapi_client.models.add_shipments_to_waybill_request import AddShipmentsToWaybillRequest
from openapi_client.models.address import Address
from openapi_client.models.assortment import Assortment
from openapi_client.models.authorization_type import AuthorizationType
from openapi_client.models.cancel_waybill_request import CancelWaybillRequest
from openapi_client.models.certificate import Certificate
from openapi_client.models.certificate_claim import CertificateClaim
from openapi_client.models.consolidated_act import ConsolidatedAct
from openapi_client.models.consolidated_act_all_of import ConsolidatedActAllOf
from openapi_client.models.contact_person import ContactPerson
from openapi_client.models.contract_for_transfer_of_cutting_rights import ContractForTransferOfCuttingRights
from openapi_client.models.coordinates import Coordinates
from openapi_client.models.forest_act import ForestAct
from openapi_client.models.forest_notice import ForestNotice
from openapi_client.models.forest_notice_all_of import ForestNoticeAllOf
from openapi_client.models.holding_base import HoldingBase
from openapi_client.models.inventory_act import InventoryAct
from openapi_client.models.inventory_act_all_of import InventoryActAllOf
from openapi_client.models.measurement_act import MeasurementAct
from openapi_client.models.measurement_unit import MeasurementUnit
from openapi_client.models.organization import Organization
from openapi_client.models.owner import Owner
from openapi_client.models.pack import Pack
from openapi_client.models.pack_location import PackLocation
from openapi_client.models.paged_result_of_assortment import PagedResultOfAssortment
from openapi_client.models.paged_result_of_certificate import PagedResultOfCertificate
from openapi_client.models.paged_result_of_measurement_act import PagedResultOfMeasurementAct
from openapi_client.models.paged_result_of_measurement_unit import PagedResultOfMeasurementUnit
from openapi_client.models.paged_result_of_organization import PagedResultOfOrganization
from openapi_client.models.paged_result_of_place_of_delivery import PagedResultOfPlaceOfDelivery
from openapi_client.models.paged_result_of_waybill import PagedResultOfWaybill
from openapi_client.models.place_of_delivery import PlaceOfDelivery
from openapi_client.models.previous_owner import PreviousOwner
from openapi_client.models.problem_details import ProblemDetails
from openapi_client.models.put_place_of_delivery_request import PutPlaceOfDeliveryRequest
from openapi_client.models.receiver import Receiver
from openapi_client.models.representer import Representer
from openapi_client.models.sales_contract import SalesContract
from openapi_client.models.sales_contract_all_of import SalesContractAllOf
from openapi_client.models.shipment import Shipment
from openapi_client.models.shipment_assortment import ShipmentAssortment
from openapi_client.models.shipment_item import ShipmentItem
from openapi_client.models.source import Source
from openapi_client.models.start_waybill_request import StartWaybillRequest
from openapi_client.models.transport import Transport
from openapi_client.models.transporter import Transporter
from openapi_client.models.unload_waybill_request import UnloadWaybillRequest
from openapi_client.models.validation_result import ValidationResult
from openapi_client.models.viewer import Viewer
from openapi_client.models.waybill import Waybill
from openapi_client.models.waybill_authorization import WaybillAuthorization
from openapi_client.models.waybill_place_of_delivery import WaybillPlaceOfDelivery
from openapi_client.models.waybill_sort_field import WaybillSortField
from openapi_client.models.waybill_status import WaybillStatus
