# coding: utf-8

"""
    EVR API

    OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pyevr.openapi_client.configuration import Configuration


class Assortment(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'code': 'str',
        'product_group_code': 'str',
        'name': 'str',
        'measurement_unit_code': 'str'
    }

    attribute_map = {
        'code': 'code',
        'product_group_code': 'productGroupCode',
        'name': 'name',
        'measurement_unit_code': 'measurementUnitCode'
    }

    def __init__(self, code=None, product_group_code=None, name=None, measurement_unit_code=None, local_vars_configuration=None):  # noqa: E501
        """Assortment - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._code = None
        self._product_group_code = None
        self._name = None
        self._measurement_unit_code = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if product_group_code is not None:
            self.product_group_code = product_group_code
        if name is not None:
            self.name = name
        if measurement_unit_code is not None:
            self.measurement_unit_code = measurement_unit_code

    @property
    def code(self):
        """Gets the code of this Assortment.  # noqa: E501

        Sortimendi kood  # noqa: E501

        :return: The code of this Assortment.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Assortment.

        Sortimendi kood  # noqa: E501

        :param code: The code of this Assortment.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def product_group_code(self):
        """Gets the product_group_code of this Assortment.  # noqa: E501

        Sortimendi tootegrupp  # noqa: E501

        :return: The product_group_code of this Assortment.  # noqa: E501
        :rtype: str
        """
        return self._product_group_code

    @product_group_code.setter
    def product_group_code(self, product_group_code):
        """Sets the product_group_code of this Assortment.

        Sortimendi tootegrupp  # noqa: E501

        :param product_group_code: The product_group_code of this Assortment.  # noqa: E501
        :type: str
        """

        self._product_group_code = product_group_code

    @property
    def name(self):
        """Gets the name of this Assortment.  # noqa: E501

        Sortimendi nimi  # noqa: E501

        :return: The name of this Assortment.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Assortment.

        Sortimendi nimi  # noqa: E501

        :param name: The name of this Assortment.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def measurement_unit_code(self):
        """Gets the measurement_unit_code of this Assortment.  # noqa: E501

        Sortimendi mõõtühik  # noqa: E501

        :return: The measurement_unit_code of this Assortment.  # noqa: E501
        :rtype: str
        """
        return self._measurement_unit_code

    @measurement_unit_code.setter
    def measurement_unit_code(self, measurement_unit_code):
        """Sets the measurement_unit_code of this Assortment.

        Sortimendi mõõtühik  # noqa: E501

        :param measurement_unit_code: The measurement_unit_code of this Assortment.  # noqa: E501
        :type: str
        """

        self._measurement_unit_code = measurement_unit_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Assortment):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Assortment):
            return True

        return self.to_dict() != other.to_dict()
