# coding: utf-8

"""
EVR API

OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.

The version of the OpenAPI document: 1.35.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class AuthorizationType(str, Enum):
    """ """

    """
    allowed enum values
    """
    FORVIEWING = "forViewing"
    FORMEASURING = "forMeasuring"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AuthorizationType from a JSON string"""
        return cls(json.loads(json_str))
