# coding: utf-8

"""
EVR API

OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.

The version of the OpenAPI document: 2.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated, Self

from pyevr.openapi_client.models.certificate_type import CertificateType


class CertificateStatement(BaseModel):
    """
    CertificateStatement
    """  # noqa: E501

    certificate_type: CertificateType = Field(alias="certificateType")
    certificate_number: Annotated[
        str, Field(min_length=0, strict=True, max_length=50)
    ] = Field(
        description="Asutusele väljastatud sertifikaadi number",
        alias="certificateNumber",
    )
    percent: Optional[
        Union[
            Annotated[float, Field(le=100.0, strict=True, ge=0.0)],
            Annotated[int, Field(le=100, strict=True, ge=0)],
        ]
    ] = Field(
        default=None,
        description="Kohustuslik ja lubatud ainult tüüpide 'FscMixPercent' ja 'PefcCertified' puhul.",
    )
    __properties: ClassVar[List[str]] = [
        "certificateType",
        "certificateNumber",
        "percent",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CertificateStatement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if percent (nullable) is None
        # and model_fields_set contains the field
        if self.percent is None and "percent" in self.model_fields_set:
            _dict["percent"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CertificateStatement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "certificateType": obj.get("certificateType"),
                "certificateNumber": obj.get("certificateNumber"),
                "percent": obj.get("percent"),
            }
        )
        return _obj
