# coding: utf-8

"""
EVR API

OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.

The version of the OpenAPI document: 1.35.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class DefectCode(str, Enum):
    """ """

    """
    allowed enum values
    """
    PEE = "pee"
    JAM = "jam"
    LYH = "lyh"
    PIK = "pik"
    KAA = "kaa"
    MET = "met"
    MAD = "mad"
    KOV = "kov"
    OKS = "oks"
    RIK = "rik"
    YTO = "yto"
    SIN = "sin"
    PUT = "put"
    TAH = "tah"
    TYY = "tyy"
    MUU = "muu"
    VPL = "vpl"
    SYD = "syd"
    LOH = "loh"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DefectCode from a JSON string"""
        return cls(json.loads(json_str))
