# coding: utf-8

"""
EVR API

OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.

The version of the OpenAPI document: 2.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated, Self


class Impregnation(BaseModel):
    """
    Impregnation
    """  # noqa: E501

    name: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(
        default=None, description="Immutusprotsessi nimi."
    )
    chemical: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(
        default=None, description="Kaitsmiseks kasutatud aine."
    )
    level: Optional[Annotated[int, Field(le=6, strict=True, ge=1)]] = Field(
        default=None, description="Väärtused peaksid olema vahemikus 1..6."
    )
    notes: Optional[Annotated[str, Field(strict=True, max_length=400)]] = Field(
        default=None, description="Lisamärkused."
    )
    source_id: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Kauba lähetaja infosüsteemi identifikaator.",
        alias="sourceId",
    )
    target_id: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Kauba saaja infosüsteemi identifikaator.",
        alias="targetId",
    )
    custom_data: Optional[Any] = Field(
        default=None,
        description="Api kasutaja poolt kohandatavad andmed.",
        alias="customData",
    )
    __properties: ClassVar[List[str]] = [
        "name",
        "chemical",
        "level",
        "notes",
        "sourceId",
        "targetId",
        "customData",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Impregnation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict["name"] = None

        # set to None if chemical (nullable) is None
        # and model_fields_set contains the field
        if self.chemical is None and "chemical" in self.model_fields_set:
            _dict["chemical"] = None

        # set to None if level (nullable) is None
        # and model_fields_set contains the field
        if self.level is None and "level" in self.model_fields_set:
            _dict["level"] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict["notes"] = None

        # set to None if source_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_id is None and "source_id" in self.model_fields_set:
            _dict["sourceId"] = None

        # set to None if target_id (nullable) is None
        # and model_fields_set contains the field
        if self.target_id is None and "target_id" in self.model_fields_set:
            _dict["targetId"] = None

        # set to None if custom_data (nullable) is None
        # and model_fields_set contains the field
        if self.custom_data is None and "custom_data" in self.model_fields_set:
            _dict["customData"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Impregnation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "chemical": obj.get("chemical"),
                "level": obj.get("level"),
                "notes": obj.get("notes"),
                "sourceId": obj.get("sourceId"),
                "targetId": obj.get("targetId"),
                "customData": obj.get("customData"),
            }
        )
        return _obj
