# coding: utf-8

"""
    EVR API

    OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.

    The version of the OpenAPI document: 1.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg


class PackLocation(str, Enum):
    """ """

    """
    allowed enum values
    """
    VAN = "van"
    TRAILER = "trailer"

    @classmethod
    def from_json(cls, json_str: str) -> "PackLocation":
        """Create an instance of PackLocation from a JSON string"""
        return PackLocation(json.loads(json_str))
