# coding: utf-8

"""
EVR API

OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.

The version of the OpenAPI document: 2.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing_extensions import Annotated, Self

from pyevr.openapi_client.models.straps import Straps


class Packing(BaseModel):
    """
    Packing
    """  # noqa: E501

    plastic_sides: Optional[Annotated[int, Field(le=1000000, strict=True, ge=0)]] = (
        Field(
            default=None,
            description="Kui mitu paki külge plastikku mähkida, tavalised väärtused on 1 ja 5.",
            alias="plasticSides",
        )
    )
    plastic_specification: Optional[
        Annotated[str, Field(strict=True, max_length=200)]
    ] = Field(
        default=None,
        description="Kasutatakse juhul, kui pooled vajavad erinevatele pakkidele erinevat tüüpi plastikuid ja peavad neid eristama.",
        alias="plasticSpecification",
    )
    pallet: Optional[StrictBool] = Field(
        default=None, description="EUR/EPAL - alusplokk paki all."
    )
    columns: Optional[Annotated[int, Field(le=1000000, strict=True, ge=0)]] = Field(
        default=None,
        description="Kui palju tükke (laudu) on pakis horisontaalselt ühes kihis.",
    )
    rows: Optional[Annotated[int, Field(le=1000000, strict=True, ge=0)]] = Field(
        default=None,
        description="Kui palju tükke (laudu) on pakis vertikaalselt = kui palju kihte.",
    )
    sticks_count: Optional[Annotated[int, Field(le=1000000, strict=True, ge=0)]] = (
        Field(
            default=None,
            description="Kui palju vahelaudu ühes kihis (samal tasemel (horisontaalselt)).",
            alias="sticksCount",
        )
    )
    sticks_layers: Optional[Annotated[int, Field(le=1000000, strict=True, ge=0)]] = (
        Field(
            default=None,
            description="Mitme kihi järel vahelaudu kasutada. Väärtus 1 tähendab vahelaudu iga kihi vahel.",
            alias="sticksLayers",
        )
    )
    straps_count: Optional[Annotated[int, Field(le=1000000, strict=True, ge=0)]] = (
        Field(
            default=None,
            description="Kui palju rihmlinte paki ümber panna.",
            alias="strapsCount",
        )
    )
    straps_type: Optional[Straps] = Field(default=None, alias="strapsType")
    labels_count: Optional[Annotated[int, Field(le=1000000, strict=True, ge=0)]] = (
        Field(
            default=None,
            description="Kui palju pakimärgiseid peale panna.",
            alias="labelsCount",
        )
    )
    labels_placement: Optional[Annotated[str, Field(strict=True, max_length=200)]] = (
        Field(
            default=None,
            description="Kasutatakse juhul, kui pooled vajavad erinevat loogikat märgiste paigutamiseks (sama arvu märgiste korral) erinevatele pakkidele.",
            alias="labelsPlacement",
        )
    )
    source_id: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Kauba lähetaja infosüsteemi identifikaator.",
        alias="sourceId",
    )
    target_id: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Kauba saaja infosüsteemi identifikaator.",
        alias="targetId",
    )
    custom_data: Optional[Any] = Field(
        default=None,
        description="Api kasutaja poolt kohandatavad andmed.",
        alias="customData",
    )
    name: Annotated[str, Field(min_length=0, strict=True, max_length=200)] = Field(
        description="Paki nimetus"
    )
    __properties: ClassVar[List[str]] = [
        "plasticSides",
        "plasticSpecification",
        "pallet",
        "columns",
        "rows",
        "sticksCount",
        "sticksLayers",
        "strapsCount",
        "strapsType",
        "labelsCount",
        "labelsPlacement",
        "sourceId",
        "targetId",
        "customData",
        "name",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Packing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if plastic_sides (nullable) is None
        # and model_fields_set contains the field
        if self.plastic_sides is None and "plastic_sides" in self.model_fields_set:
            _dict["plasticSides"] = None

        # set to None if plastic_specification (nullable) is None
        # and model_fields_set contains the field
        if (
            self.plastic_specification is None
            and "plastic_specification" in self.model_fields_set
        ):
            _dict["plasticSpecification"] = None

        # set to None if pallet (nullable) is None
        # and model_fields_set contains the field
        if self.pallet is None and "pallet" in self.model_fields_set:
            _dict["pallet"] = None

        # set to None if columns (nullable) is None
        # and model_fields_set contains the field
        if self.columns is None and "columns" in self.model_fields_set:
            _dict["columns"] = None

        # set to None if rows (nullable) is None
        # and model_fields_set contains the field
        if self.rows is None and "rows" in self.model_fields_set:
            _dict["rows"] = None

        # set to None if sticks_count (nullable) is None
        # and model_fields_set contains the field
        if self.sticks_count is None and "sticks_count" in self.model_fields_set:
            _dict["sticksCount"] = None

        # set to None if sticks_layers (nullable) is None
        # and model_fields_set contains the field
        if self.sticks_layers is None and "sticks_layers" in self.model_fields_set:
            _dict["sticksLayers"] = None

        # set to None if straps_count (nullable) is None
        # and model_fields_set contains the field
        if self.straps_count is None and "straps_count" in self.model_fields_set:
            _dict["strapsCount"] = None

        # set to None if labels_count (nullable) is None
        # and model_fields_set contains the field
        if self.labels_count is None and "labels_count" in self.model_fields_set:
            _dict["labelsCount"] = None

        # set to None if labels_placement (nullable) is None
        # and model_fields_set contains the field
        if (
            self.labels_placement is None
            and "labels_placement" in self.model_fields_set
        ):
            _dict["labelsPlacement"] = None

        # set to None if source_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_id is None and "source_id" in self.model_fields_set:
            _dict["sourceId"] = None

        # set to None if target_id (nullable) is None
        # and model_fields_set contains the field
        if self.target_id is None and "target_id" in self.model_fields_set:
            _dict["targetId"] = None

        # set to None if custom_data (nullable) is None
        # and model_fields_set contains the field
        if self.custom_data is None and "custom_data" in self.model_fields_set:
            _dict["customData"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Packing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "plasticSides": obj.get("plasticSides"),
                "plasticSpecification": obj.get("plasticSpecification"),
                "pallet": obj.get("pallet"),
                "columns": obj.get("columns"),
                "rows": obj.get("rows"),
                "sticksCount": obj.get("sticksCount"),
                "sticksLayers": obj.get("sticksLayers"),
                "strapsCount": obj.get("strapsCount"),
                "strapsType": obj.get("strapsType"),
                "labelsCount": obj.get("labelsCount"),
                "labelsPlacement": obj.get("labelsPlacement"),
                "sourceId": obj.get("sourceId"),
                "targetId": obj.get("targetId"),
                "customData": obj.get("customData"),
                "name": obj.get("name"),
            }
        )
        return _obj
