# coding: utf-8

"""
EVR API

OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.

The version of the OpenAPI document: 2.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated, Self

from pyevr.openapi_client.models.eudr_number import EudrNumber
from pyevr.openapi_client.models.sawn_pack import SawnPack
from pyevr.openapi_client.models.sawn_wood import SawnWood


class SawnShipment(BaseModel):
    """
    SawnShipment
    """  # noqa: E501

    sawn_wood: SawnWood = Field(alias="sawnWood")
    packs: Annotated[List[SawnPack], Field(min_length=1, max_length=100)] = Field(
        description="Definitsiooni järgi on pakis ainult üks ristlõikemõõt, tamme jne puhul varieerimisega kasutame keskmist laiust või virtuaalseid alamkimpe."
    )
    row_number: Optional[Annotated[int, Field(le=1000000, strict=True, ge=0)]] = Field(
        default=None,
        description="Saadetise rea või järjekorra number.",
        alias="rowNumber",
    )
    eudr_numbers: Optional[Annotated[List[EudrNumber], Field(max_length=25)]] = Field(
        default=None,
        description="Euroopa Liidu puidu asukoha registreerimise numbrid",
        alias="eudrNumbers",
    )
    name: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(
        default=None, description="Saadetise nimi, lühikirjeldus või partiinumber."
    )
    source_id: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Kauba lähetaja infosüsteemi identifikaator.",
        alias="sourceId",
    )
    target_id: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Kauba saaja infosüsteemi identifikaator.",
        alias="targetId",
    )
    custom_data: Optional[Any] = Field(
        default=None,
        description="Api kasutaja poolt kohandatavad andmed.",
        alias="customData",
    )
    __properties: ClassVar[List[str]] = [
        "sawnWood",
        "packs",
        "rowNumber",
        "eudrNumbers",
        "name",
        "sourceId",
        "targetId",
        "customData",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SawnShipment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sawn_wood
        if self.sawn_wood:
            _dict["sawnWood"] = self.sawn_wood.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in packs (list)
        _items = []
        if self.packs:
            for _item_packs in self.packs:
                if _item_packs:
                    _items.append(_item_packs.to_dict())
            _dict["packs"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in eudr_numbers (list)
        _items = []
        if self.eudr_numbers:
            for _item_eudr_numbers in self.eudr_numbers:
                if _item_eudr_numbers:
                    _items.append(_item_eudr_numbers.to_dict())
            _dict["eudrNumbers"] = _items
        # set to None if row_number (nullable) is None
        # and model_fields_set contains the field
        if self.row_number is None and "row_number" in self.model_fields_set:
            _dict["rowNumber"] = None

        # set to None if eudr_numbers (nullable) is None
        # and model_fields_set contains the field
        if self.eudr_numbers is None and "eudr_numbers" in self.model_fields_set:
            _dict["eudrNumbers"] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict["name"] = None

        # set to None if source_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_id is None and "source_id" in self.model_fields_set:
            _dict["sourceId"] = None

        # set to None if target_id (nullable) is None
        # and model_fields_set contains the field
        if self.target_id is None and "target_id" in self.model_fields_set:
            _dict["targetId"] = None

        # set to None if custom_data (nullable) is None
        # and model_fields_set contains the field
        if self.custom_data is None and "custom_data" in self.model_fields_set:
            _dict["customData"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SawnShipment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "sawnWood": SawnWood.from_dict(obj["sawnWood"])
                if obj.get("sawnWood") is not None
                else None,
                "packs": [SawnPack.from_dict(_item) for _item in obj["packs"]]
                if obj.get("packs") is not None
                else None,
                "rowNumber": obj.get("rowNumber"),
                "eudrNumbers": [
                    EudrNumber.from_dict(_item) for _item in obj["eudrNumbers"]
                ]
                if obj.get("eudrNumbers") is not None
                else None,
                "name": obj.get("name"),
                "sourceId": obj.get("sourceId"),
                "targetId": obj.get("targetId"),
                "customData": obj.get("customData"),
            }
        )
        return _obj
