# coding: utf-8

"""
EVR API

OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.

The version of the OpenAPI document: 2.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated, Self

from pyevr.openapi_client.models.impregnation import Impregnation
from pyevr.openapi_client.models.seasoning import Seasoning
from pyevr.openapi_client.models.shape import Shape
from pyevr.openapi_client.models.surface import Surface


class Treatment(BaseModel):
    """
    Treatment
    """  # noqa: E501

    name: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(
        default=None,
        description="Nime/koodi tähendus on poolte vahel eelnevalt kokku lepitud. Mõned klassikalised näited on KK10% Tanalith, Must värvitud teritatud, Intensiivne-termo soontega.",
    )
    seasoning: Optional[Seasoning] = None
    impregnation: Optional[Impregnation] = None
    surface: Optional[Surface] = None
    shape: Optional[Shape] = None
    other: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(
        default=None,
        description="Kõik muud omadused Töötlusüksuse definitsioonis kirjeldatud, mis ei kuulu allpool ühegi komponendi alla, nt. kaubamärgiga märgistatud.",
    )
    notes: Optional[Annotated[str, Field(strict=True, max_length=400)]] = Field(
        default=None, description="Lisamärkused."
    )
    source_id: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Kauba lähetaja infosüsteemi identifikaator.",
        alias="sourceId",
    )
    target_id: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="Kauba saaja infosüsteemi identifikaator.",
        alias="targetId",
    )
    custom_data: Optional[Any] = Field(
        default=None,
        description="Api kasutaja poolt kohandatavad andmed.",
        alias="customData",
    )
    __properties: ClassVar[List[str]] = [
        "name",
        "seasoning",
        "impregnation",
        "surface",
        "shape",
        "other",
        "notes",
        "sourceId",
        "targetId",
        "customData",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Treatment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of seasoning
        if self.seasoning:
            _dict["seasoning"] = self.seasoning.to_dict()
        # override the default output from pydantic by calling `to_dict()` of impregnation
        if self.impregnation:
            _dict["impregnation"] = self.impregnation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of surface
        if self.surface:
            _dict["surface"] = self.surface.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shape
        if self.shape:
            _dict["shape"] = self.shape.to_dict()
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict["name"] = None

        # set to None if other (nullable) is None
        # and model_fields_set contains the field
        if self.other is None and "other" in self.model_fields_set:
            _dict["other"] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict["notes"] = None

        # set to None if source_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_id is None and "source_id" in self.model_fields_set:
            _dict["sourceId"] = None

        # set to None if target_id (nullable) is None
        # and model_fields_set contains the field
        if self.target_id is None and "target_id" in self.model_fields_set:
            _dict["targetId"] = None

        # set to None if custom_data (nullable) is None
        # and model_fields_set contains the field
        if self.custom_data is None and "custom_data" in self.model_fields_set:
            _dict["customData"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Treatment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "seasoning": Seasoning.from_dict(obj["seasoning"])
                if obj.get("seasoning") is not None
                else None,
                "impregnation": Impregnation.from_dict(obj["impregnation"])
                if obj.get("impregnation") is not None
                else None,
                "surface": Surface.from_dict(obj["surface"])
                if obj.get("surface") is not None
                else None,
                "shape": Shape.from_dict(obj["shape"])
                if obj.get("shape") is not None
                else None,
                "other": obj.get("other"),
                "notes": obj.get("notes"),
                "sourceId": obj.get("sourceId"),
                "targetId": obj.get("targetId"),
                "customData": obj.get("customData"),
            }
        )
        return _obj
