# coding: utf-8

"""
    EVR API

    OpenAPI Generator'i jaoks kohandatud EVR API kirjeldus. Kasuta seda juhul, kui spetsifikatsioonile vastava EVR API kirjeldusega ei õnnestu klienti genereerida.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pyevr.openapi_client.configuration import Configuration


class WaybillNote(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'creator': 'WaybillNoteCreator',
        'creation_time': 'datetime',
        'message': 'str'
    }

    attribute_map = {
        'creator': 'creator',
        'creation_time': 'creationTime',
        'message': 'message'
    }

    def __init__(self, creator=None, creation_time=None, message=None, local_vars_configuration=None):  # noqa: E501
        """WaybillNote - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._creator = None
        self._creation_time = None
        self._message = None
        self.discriminator = None

        if creator is not None:
            self.creator = creator
        if creation_time is not None:
            self.creation_time = creation_time
        if message is not None:
            self.message = message

    @property
    def creator(self):
        """Gets the creator of this WaybillNote.  # noqa: E501


        :return: The creator of this WaybillNote.  # noqa: E501
        :rtype: WaybillNoteCreator
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this WaybillNote.


        :param creator: The creator of this WaybillNote.  # noqa: E501
        :type: WaybillNoteCreator
        """

        self._creator = creator

    @property
    def creation_time(self):
        """Gets the creation_time of this WaybillNote.  # noqa: E501

        Loomise aeg  # noqa: E501

        :return: The creation_time of this WaybillNote.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """Sets the creation_time of this WaybillNote.

        Loomise aeg  # noqa: E501

        :param creation_time: The creation_time of this WaybillNote.  # noqa: E501
        :type: datetime
        """

        self._creation_time = creation_time

    @property
    def message(self):
        """Gets the message of this WaybillNote.  # noqa: E501

        Sõnum  # noqa: E501

        :return: The message of this WaybillNote.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this WaybillNote.

        Sõnum  # noqa: E501

        :param message: The message of this WaybillNote.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WaybillNote):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WaybillNote):
            return True

        return self.to_dict() != other.to_dict()
