"""Main module."""

from __future__ import annotations

import contextvars
import os
import typing

import certifi
from pydantic import BaseModel

from pyevr import apis
from pyevr.openapi_client import models
from pyevr.openapi_client.api_client import ApiClient
from pyevr.openapi_client.configuration import Configuration
from pyevr.openapi_client.models import StartWaybillRequest, Waybill

full_serialization = contextvars.ContextVar("full_serialization", default=False)

#: Truthy values accepted for the PYEVR_CERTIFI_ENABLED environment variable.
_ENV_TRUTHY = ("1", "true", "yes", "on")


def _certifi_enabled() -> bool:
    return os.environ.get("PYEVR_CERTIFI_ENABLED", "1").strip().lower() in _ENV_TRUTHY


#: Discriminator values assumed for data serialized before the discriminator
#: existed. EVR 2.0.0 introduced waybill types; everything before was a forest waybill.
LEGACY_DISCRIMINATOR_DEFAULTS = {
    Waybill: "forest",
    StartWaybillRequest: "forest",
}


def _discriminator_info(model_cls):
    """Return ``(base_cls, property_name, value_class_map)`` for models using a discriminator.

    The generated abstract models keep the discriminator mapping in name-mangled class
    attributes; concrete subclasses inherit them, so walk the MRO to find the owner.
    """
    for klass in model_cls.__mro__:
        class_map = getattr(
            klass, f"_{klass.__name__}__discriminator_value_class_map", None
        )
        if class_map is not None:
            return (
                klass,
                getattr(klass, f"_{klass.__name__}__discriminator_property_name"),
                class_map,
            )
    return None


def _model_classes_in(annotation):
    """Collect pydantic model classes referenced by a field annotation (Optional/List/Union/Annotated)."""
    if isinstance(annotation, type):
        return [annotation] if issubclass(annotation, BaseModel) else []
    found = []
    for arg in typing.get_args(annotation):
        found.extend(_model_classes_in(arg))
    return found


def normalize_for_model(data, model_cls):
    """Convert data produced by :meth:`ExtendedApiClient.serialize_fully` into the shape ``from_dict`` expects.

    The generated ``from_dict`` methods only read JSON aliases (camelCase) and require the
    discriminator property to be present. Fully serialized data uses python attribute names
    (snake_case) and data stored before a discriminator was introduced may lack it. This
    function, recursively:

    * renames snake_case attribute names to their aliases where the alias is absent,
    * fills in a missing discriminator using :data:`LEGACY_DISCRIMINATOR_DEFAULTS` (or, for
      a concrete subclass, the value that maps to it),
    * resolves the concrete subclass of discriminated models so their own fields are handled.

    Data already in the alias form passes through unchanged.
    """
    if not isinstance(data, dict):
        return data

    data = dict(data)
    info = _discriminator_info(model_cls)
    if info is not None:
        base_cls, prop, class_map = info
        if data.get(prop) is None:
            if model_cls is base_cls:
                default = LEGACY_DISCRIMINATOR_DEFAULTS.get(base_cls)
            else:
                default = next(
                    (k for k, v in class_map.items() if v == model_cls.__name__), None
                )
            if default is not None:
                data[prop] = default
        concrete_name = class_map.get(data.get(prop))
        concrete_cls = getattr(models, concrete_name, None) if concrete_name else None
        if concrete_cls is not None:
            model_cls = concrete_cls

    for name, field in model_cls.model_fields.items():
        alias = field.alias or name
        if alias not in data and name in data:
            data[alias] = data.pop(name)
        if alias not in data:
            continue
        nested = _model_classes_in(field.annotation)
        if len(nested) != 1:
            continue
        value = data[alias]
        if isinstance(value, list):
            data[alias] = [normalize_for_model(item, nested[0]) for item in value]
        else:
            data[alias] = normalize_for_model(value, nested[0])
    return data


class ExtendedApiClient(ApiClient):
    """Extended API client generated by openapi-generator-cli."""

    @classmethod
    def deserialize_data(cls, response_data, response_type):
        """Deserializes parsed json into an object.

        Accepts both API-shaped data (camelCase aliases) and the output of
        :meth:`serialize_fully` / :meth:`EVRClient.sanitize_for_serialization`
        (snake_case attribute names). Waybill data stored before EVR 2.0.0, which
        lacks the ``type`` discriminator, is treated as a forest waybill.

        :param response_data: parsed json to be deserialized.
        :param response_type: class literal for deserialized object.

        :return: deserialized object.
        """
        return response_type.from_dict(
            normalize_for_model(response_data, response_type)
        )

    def sanitize_for_serialization(self, obj):
        if hasattr(obj, "actual_instance"):
            return self.sanitize_for_serialization(obj.actual_instance)

        if full_serialization.get() and isinstance(obj, BaseModel):
            return super().sanitize_for_serialization(obj.__dict__)

        return super().sanitize_for_serialization(obj)

    def serialize_fully(self, obj):
        token = full_serialization.set(True)
        try:
            result = self.sanitize_for_serialization(obj)
        finally:
            full_serialization.reset(token)
        return result


class EVRClient:
    """API client class for EVR.

    :param api_key: Company API key in EVR
    :param host: EVR host. Defaults to test host (optional)

    TLS peer verification uses the ``certifi`` CA bundle by default, so
    behavior does not depend on the age of the system CA store (e.g. old
    Docker base images). Set the environment variable
    ``PYEVR_CERTIFI_ENABLED`` to a falsy value (``0``/``false``/``no``/
    ``off``) to verify against the system CA store instead — needed when
    the system store carries extra CAs, such as a corporate TLS proxy
    certificate or a private test instance CA.
    """

    openapi_client_class = ExtendedApiClient

    def __init__(self, api_key: str, host: str | None = None):
        configuration = Configuration(api_key={"SecretApiKey": api_key})
        if host is not None:
            configuration.host = host
        if _certifi_enabled():
            configuration.ssl_ca_cert = certifi.where()
        self.openapi_client = self.openapi_client_class(configuration)

        self.assortments = apis.AssortmentsAPI(self.openapi_client)
        self.certificates = apis.CertificatesAPI(self.openapi_client)
        self.measurements = apis.MeasurementsAPI(self.openapi_client)
        self.measurement_units = apis.MeasurementUnitsAPI(self.openapi_client)
        self.organizations = apis.OrganizationsAPI(self.openapi_client)
        self.place_of_deliveries = apis.PlaceOfDeliveriesAPI(self.openapi_client)
        self.waybills = apis.WaybillsAPI(self.openapi_client)

    @classmethod
    def deserialize_data(cls, response_data, response_type):
        return cls.openapi_client_class.deserialize_data(response_data, response_type)

    @classmethod
    def sanitize_for_serialization(cls, api_model):
        return cls.openapi_client_class().serialize_fully(api_model)
